[tox]
envlist = 
    py37-django22
    flake8

[testenv]
deps=
    -r{toxinidir}/requirements/default.txt
    -r{toxinidir}/requirements/test.txt
    -r{toxinidir}/requirements/test-ci.txt
    django22: -r{toxinidir}/requirements/test-django22.txt

sitepackages = False
recreate = True
commands =
    python -m pip install pip==21.3.1
    pip install celery==4.4.7
    pip install kombu==4.6.11
    pip install importlib_metadata==4.12.0
    pytest -xvs -k "not test_store_result"

[testenv:flake8]
deps =
    flake8
commands =
    python -m pip install pip==21.3.1
    flake8 {toxinidir}/django_celery_results {toxinidir}/t
