[tox]
envlist =
    py38-django{32}
    ; py38-django{32,40,41,42}

    flake8
    integration

[travis:env]
DJANGO =
    3.2: django32
    ; 4.0: django40
    ; 4.1: django41
    ; 4.2: django42

[testenv]
basepython = python3.8
deps=
    -r{toxinidir}/requirements/default.txt
    -r{toxinidir}/requirements/test.txt
    -r{toxinidir}/requirements/test-ci.txt

    django32: -r{toxinidir}/requirements/test-django32.txt
    ; django40: -r{toxinidir}/requirements/test-django40.txt
    ; django41: -r{toxinidir}/requirements/test-django41.txt
    ; django42: -r{toxinidir}/requirements/test-django42.txt

    integration: -r{toxinidir}/requirements/test-django.txt
    flake8: -r{toxinidir}/requirements/pkgutils.txt
sitepackages = False
recreate = True
commands =
    pip install pytz>=2019.3
    pip install {toxinidir}/wheels/celery-4.4.7-py2.py3-none-any.whl
    pip install -U kombu==4.6.11
    pytest -xvs -k "not test_store_result"

[testenv:flake8]
basepython = python3.8
flake8>=3.7.0
commands =
    flake8 {toxinidir}/django_celery_results {toxinidir}/t
    pip install -U kombu==4.6.11

[testenv:integration]
basepython = python3.8
commands =
    pip install {toxinidir}/wheels/celery-4.4.7-py2.py3-none-any.whl
    pip install -U kombu==4.6.11
    pytest -B -xv -k "not test_store_result"